thenewboston-developers/thenewboston-Backend

thenewboston/orders/consumers/order.py, thenewboston/orders/order_matching/order_matching_engine.py, thenewboston/wallets/consumers/wallet.py
=> 29 - Filled orders remaining in order book

thenewboston/exchange/models/exchange_order.py, thenewboston/exchange/order_matching/order_matching_engine.py, thenewboston/exchange/serializers/exchange_order.py, thenewboston/exchange/views/exchange_order.py
=> 36 - Rename OrderType enum

poetry.lock, pyproject.toml
=> 42 - pytest and model bakery should be under the development dependencies

thenewboston/users/serializers/user.py
=> 51 - Recipient not being set after accepting invitation

thenewboston/art/views/artwork.py
=> 58 - Edit and delete artwork

thenewboston/art/filters/artwork_transfer.py, thenewboston/art/views/artwork_transfer.py
=> 62 - Fetch artwork transfers by ID

thenewboston/art/filters/artwork.py
=> 66 - Marketplace updates

thenewboston/users/serializers/user.py
=> 68 - Alphanumeric username validation

thenewboston/art/serializers/openai_image.py, thenewboston/art/views/openai_image.py
=> 72 - Allow for multiple images to be created at once

Makefile, thenewboston/art/views/openai_image.py
=> 77 - Fix /openai_images 500

thenewboston/art/serializers/artwork_transfer.py
=> 76 - When you transfer an artwork it should no longer be for sale

thenewboston/exchange/filters/trade.py
=> 81 - Add filters for trade page

thenewboston/social/serializers/post.py
=> 87 - Remaining images fix

README.md
Updates the README.md with some basic instructions on how to setup this project locally.
Will be adding more instructions/documentation gradually, which will help us onboard new engineers
=> docs: README.md improved

thenewboston/social/serializers/post.py
Related Issue: https://github.com/thenewboston-developers/thenewboston-Frontend/issues/166
Frontend PR: https://github.com/thenewboston-developers/thenewboston-Frontend/pull/168
=> fix: image lost when editing post

thenewboston/project/__init__.py
Was getting this error when calling POST `/api/messages`:
- https://stackoverflow.com/questions/68167239/celery-no-hostname-was-supplied-reverting-to-default-localhost
- https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html
=> GitHub integration review

DEPLOY.md
=> 154 - readme typo fixed

thenewboston/users/serializers/user.py
=> 147 - AttributeError /api/users

thenewboston/university/serializers/course.py, thenewboston/university/serializers/lecture.py
Closes #169 
Frontend PR: https://github.com/thenewboston-developers/thenewboston-Frontend/pull/266
=> 169 - passing publication status actual value instead of boolean

thenewboston/users/serializers/stats.py, thenewboston/users/urls.py, thenewboston/users/views/stats.py
Closes #164 
- Introduces a new API to fetch user stats: `base_url.../user/<user_id>/stats`
- Frontend PR: https://github.com/thenewboston-developers/thenewboston-Frontend/pull/267
=> feat: API to get user stats

thenewboston/notifications/admin.py, thenewboston/notifications/views/notification.py
=> 167 - api to mark all unread notifications as read

thenewboston/general/clients/openai.py, thenewboston/github/models/pull.py, thenewboston/ia/views/message.py, thenewboston/project/tasks.py
=> add metadata for promptlayer for conversational requests

thenewboston/ia/serializers/ia.py, thenewboston/ia/urls.py, thenewboston/ia/views/ia.py
=> 165 - API to get Ia

thenewboston/social/serializers/follower.py, thenewboston/social/views/follower.py
No BE Ticket.
FE Ticket: https://github.com/thenewboston-developers/thenewboston-Frontend/issues/288
=> 288 - destroy/delete method overridden to take following user id instead of follower id + self_following field added

README.md
=> 191 - Type in Readme

thenewboston/contributions/serializers/contribution.py, thenewboston/contributions/tests/test_contributions_api.py, thenewboston/contributions/utils/contribution.py, thenewboston/contributions/views/contribution.py
Related to https://github.com/thenewboston-developers/thenewboston-Backend/issues/166
- Contributions Pagination
- Separate endpoint to get top contributors
- Separate endpoint to get cumulative contributions
=> contributions pagination + separate endpoints for Top Contributors and Cumulative Contributors

thenewboston/discord/bot.py, thenewboston/discord/tests/test_bot.py
=> 225 - Discord bot improvements

thenewboston/social/views/comment.py
=> 142 - Post Comments Notifications

thenewboston/general/enums.py
=> 247 - Remove CREATE_MESSAGE

thenewboston/exchange/urls.py, thenewboston/invitations/urls.py, thenewboston/notifications/views/notification.py, thenewboston/social/urls.py, thenewboston/wallets/views/wallet.py
=> 248 - Update URLs to be kebab-case

thenewboston/project/routing.py
=> 262 - Update /ws/exchange_orders to be kebab-case

thenewboston/currencies/serializers/mint.py, thenewboston/exchange/order_matching/order_matching_engine.py, thenewboston/exchange/views/exchange_order.py, thenewboston/general/utils/transfers.py, thenewboston/social/serializers/comment.py, thenewboston/social/serializers/post.py, thenewboston/social/views/comment.py
=> 264 - Notification images broken

thenewboston/exchange/consumers/__init__.py, thenewboston/exchange/consumers/trade.py, thenewboston/exchange/order_matching/order_matching_engine.py, thenewboston/general/enums.py, thenewboston/project/routing.py
=> 270 - Real time chart update

thenewboston/currencies/views/currency.py
=> 272 - Ensure default currency can not be deleted

thenewboston/currencies/serializers/currency_balance.py, thenewboston/currencies/urls.py, thenewboston/currencies/views/currency_balance.py
=> 279 - Balances

thenewboston/notifications/consumers/notification.py, thenewboston/notifications/views/notification.py
=> 283 - Notification pagination

thenewboston/project/settings/templates/settings.dev.py, thenewboston/project/settings/templates/template.env
=> 285 - Fix image paths

thenewboston/currencies/filters/total_amount_minted.py, thenewboston/currencies/serializers/currency.py, thenewboston/currencies/serializers/total_amount_minted.py, thenewboston/currencies/tests/test_rest_api.py, thenewboston/currencies/urls.py, thenewboston/currencies/views/currency.py, thenewboston/currencies/views/total_amount_minted.py
=> 292 - Currency optimizations

thenewboston/exchange/filters/trade.py, thenewboston/general/models/created_modified.py
=> 298 - Standardize how we pass in IDs as query params

thenewboston/users/serializers/user.py, thenewboston/users/tests/test_username_validation.py, thenewboston/users/validators.py
=> 290 - Figure out username upper/lowercase logic

thenewboston/social/filters/post.py
=> 291 - Post should show up on sender and recipients profiles

.flake8, .pre-commit-config.yaml, thenewboston/currencies/urls.py, thenewboston/exchange/filters/chart_data.py, thenewboston/exchange/serializers/chart_data.py, thenewboston/exchange/serializers/trade.py, thenewboston/exchange/urls.py, thenewboston/exchange/views/chart_data.py, thenewboston/exchange/views/trade.py
=> 305 - Improve chart logic

thenewboston/exchange/filters/trade_price_chart_data.py, thenewboston/exchange/serializers/trade_price_chart_data.py, thenewboston/exchange/urls.py, thenewboston/exchange/views/trade_price_chart_data.py
=> 311 - Rename chart data endpoint

thenewboston/currencies/serializers/currency.py
=> 314 - Tickers must be uppercase

thenewboston/general/utils/text.py, thenewboston/social/serializers/post.py, thenewboston/social/views/comment.py, thenewboston/social/views/post_like.py
=> 336 - Improve notification UX

thenewboston/currencies/tests/test_rest_api.py, thenewboston/currencies/views/currency.py
=> 346 - Sort currencies by updated at

thenewboston/currencies/serializers/currency_balance.py, thenewboston/currencies/views/currency_balance.py
=> 349 - Currency details page updates

thenewboston/currencies/admin.py
=> 353 - Add whitepaper to Django admin

thenewboston/social/serializers/post.py, thenewboston/social/views/post.py
=> 335 - Show coin icons and amounts on posts

thenewboston/wallets/filters/wallet.py, thenewboston/wallets/views/wallet.py
=> 357 - Profile tab to see what coins other people have

thenewboston/currencies/tests/test_rest_api.py, thenewboston/currencies/views/currency.py
=> 325 - Currencies pagination

thenewboston/currencies/serializers/currency.py, thenewboston/exchange/models/exchange_order.py, thenewboston/exchange/tests/test_make_trade.py, thenewboston/general/serializers/fields.py, thenewboston/project/settings/base.py
=> 379 - Notifications optimization

thenewboston/social/serializers/comment.py, thenewboston/social/views/post.py
=> 382 - Update useCurrencyLogo logic

thenewboston/wallets/filters/wallet.py, thenewboston/wallets/views/wallet.py
=> 388 - Paginated wallets
